package:
  name: easybio
  version: 0.4.3

source:
  # path: /home/data/user/lei/code/python/easyBio_conda/easybio_conda
  path: .

build:
  number: 0

requirements:
  build:
    - python=3.10
    - setuptools
    - numpy<1.25
    - pandas
    # - requests
    # - Cython
    # Add more dependencies here
    
  run:
    - python>=3
    # - numpy>=1.20
    - pandas

test:
  imports:
    - easybio

  commands:
    - easyBio

about:
  home: https://github.com/xleizi/easyBio_conda
  license: MIT
  summary: dowload SRA data from GEO database
  description: The purpose of the creation of this package is to make bioinformatics analysis simpler.
  doc_url: https://github.com/xleizi/easyBio_conda/blob/main/README.md
  dev_url: https://github.com/xleizi/easyBio_conda
